name: Test Tap

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    # Set up DB2 image
    # Installing the Db2 Community Edition Docker image on Linux systems
    # https://www.ibm.com/docs/en/db2/11.5?topic=system-linux
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        architecture: x64
    - name: Install tap in meltano
      run: |
        pip install meltano
        meltano init testproj
        cd testproj
        meltano add extractor tap-db2 --from-ref ../tap-db2.yml || cat ${{ github.workspace }}/testproj/.meltano/logs/pip/extractors/tap-db2/pip.log
        meltano invoke tap-db2 --discover
      env:
        TAP_DB2_USERNAME: db2inst1
        TAP_DB2_PASSWORD: password
        TAP_DB2_HOSTNAME: localhost
        TAP_DB2_PORT: 50000
        TAP_DB2_DATABASE: sample
